<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://sister.com/gen/users"
           targetNamespace="http://sister.com/gen/users"
           elementFormDefault="qualified">

    <!-- Entity User -->
    <xs:complexType name="User">
        <xs:sequence>
            <xs:element name="nim" type="xs:string"/>
            <xs:element name="nama" type="xs:string"/>
            <xs:element name="umur" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <!-- CREATE -->
    <xs:element name="createUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="createUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nim" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- READ (by NIM) -->
    <xs:element name="getUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nim" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- UPDATE -->
    <xs:element name="updateUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="updateUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nim" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- DELETE -->
    <xs:element name="deleteUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nim" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deleteUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nim" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- GET ALL USERS -->
    <xs:element name="getAllUsersRequest">
        <xs:complexType/>
    </xs:element>

    <xs:element name="getAllUsersResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users" type="tns:User" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
